version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
